version: 2
jobs:
  netcore1.0:
    working_directory: ~/GraphQL.Client/
    docker:
      - image: microsoft/dotnet:1-sdk
    steps:
      - checkout

      # Test
      - run: dotnet restore
      - run: dotnet test --framework netcoreapp1.0 ./tests/GraphQL.Common.Tests/GraphQL.Common.Tests.csproj
      - run: dotnet test --framework netcoreapp1.0 ./tests/GraphQL.Client.Tests/GraphQL.Client.Tests.csproj

  netcore2.0:
    working_directory: ~/GraphQL.Client/
    docker:
      - image: microsoft/dotnet:2-sdk
    steps:
      - checkout

      # Test
      - run: dotnet test --framework netcoreapp2.0 ./tests/GraphQL.Common.Tests/GraphQL.Common.Tests.csproj
      - run: dotnet test --framework netcoreapp2.0 ./tests/GraphQL.Client.Tests/GraphQL.Client.Tests.csproj

  deploy:
    working_directory: ~/GraphQL.Client/
    docker:
      - image: microsoft/dotnet:2-sdk
    environment:
      MY_GET_SOURCE: https://www.myget.org/F/graphql-dotnet/api/v3/index.json
    steps:
      - checkout

      # Pack
      - run: dotnet build --configuration Release ./src/GraphQL.Common/GraphQL.Common.csproj
      - run: dotnet pack --configuration Release ./src/GraphQL.Common/GraphQL.Common.csproj
      - run: dotnet build --configuration Release ./src/GraphQL.Client/GraphQL.Client.csproj
      - run: dotnet pack --configuration Release ./src/GraphQL.Client/GraphQL.Client.csproj

      # Store Artifacts
      - store_artifacts:
          path: ./src/GraphQL.Common/bin/Release/GraphQL.Common.2.0.0.nupkg
      - store_artifacts:
          path: ./src/GraphQL.Client/bin/Release/GraphQL.Client.2.0.0.nupkg

      # Deploy
      - deploy:
          name: MyGet
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              dotnet nuget push ./src/GraphQL.Common/bin/Release/GraphQL.Common.2.0.0.nupkg --api-key $MY_GET_API_KEY --source $MY_GET_SOURCE
              dotnet nuget push ./src/GraphQL.Client/bin/Release/GraphQL.Client.2.0.0.nupkg --api-key $MY_GET_API_KEY --source $MY_GET_SOURCE
            fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - netcore1.0
      - netcore2.0
      - deploy:
          requires:
            - netcore1.0
            - netcore2.0
