name: Main workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - run: dotnet tool restore
#    - run: dotnet format --check --dry-run
    # - run: dotnet restore
    - run: dotnet build
    # - run: dotnet pack

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    # - run: dotnet restore
    # - run: dotnet build
    - run: dotnet test -p:ParallelizeTestCollections=false

  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '3.1.100'
    - run: dotnet restore
    - run: dotnet build --configuration Release
    - run: dotnet pack --configuration Release
    - run: dotnet nuget push ./src/GraphQL.Client/bin/Release/GraphQL.Client.*.nupkg --api-key $GITHUB_TOKEN --source https://nuget.pkg.github.com/graphql-dotnet/graphql-client/index.json
    - run: dotnet nuget push ./src/GraphQL.Client.Http/bin/Release/GraphQL.Client.*.nupkg --api-key $GITHUB_TOKEN --source https://nuget.pkg.github.com/graphql-dotnet/graphql-client/index.json
